features:
  node_user_picture: 0
  comment_user_picture: 0
  comment_user_verification: 0
  favicon: 1
logo:
  use_default: 0
  path: 'public://icon_movientt.png'
favicon:
  use_default: 1
b5_top_container: container
b5_top_container_config: ''
b5_body_schema: none
b5_body_bg_schema: none
b5_navbar_schema: dark
b5_navbar_bg_schema: primary
b5_footer_schema: light
b5_footer_bg_schema: none
subtheme_folder: themes/custom
subtheme_name: 'B5 subtheme'
subtheme_machine_name: b5subtheme
mobile_menu_all_widths: 0
site_branding_bg_color: gray
base_primary_color: '#57919e'
